#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_INTERNAL_IP:8080

echo "ACTION HOOK: start"

#nohup uwsgi --socket $OPENSHIFT_NGINX_IP:16001 -d ${OPENSHIFT_LOG_DIR}app.log --pidfile ${OPENSHIFT_TMP_DIR}uwsgi.pid --pythonpath $OPENSHIFT_REPO_DIR/wsgi/myproject/ --module myproject.wsgi:application &
nohup uwsgi --yaml ${OPENSHIFT_REPO_DIR}.openshift/uwsgi.yaml &


cd $OPENSHIFT_REPO_DIR/wsgi/myproject/

(python manage.py runworker --only-channels=websocket.* &) && 
(daphne myproject.asgi:channel_layer -p 16002 -b $OPENSHIFT_NGINX_IP &)

# (python manage.py runworker --only-channels=http.* --only-channels=websocket.* &) && 
# (daphne myproject.asgi:channel_layer -p 16002 -b $OPENSHIFT_NGINX_IP &)